// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/gin-gonic/gin"
	"main/internal/repository"
	"main/internal/repository/cache"
	"main/internal/repository/dao"
	"main/internal/service"
	"main/internal/web"
	"main/ioc"
)

// Injectors from wire.go:

func InitWebServer() *gin.Engine {
	cmdable := ioc.InitRedis()
	v := ioc.InitGinMiddlewares(cmdable)
	db := ioc.InitDB()
	userDAO := dao.NewUserDAO(db)
	userCache := cache.NewRedisUserCache(cmdable)
	userRepository := repository.NewUserRepositoryWithCache(userDAO, userCache)
	userService := service.NewUserServiceV1(userRepository)
	authCodeCache := cache.NewRedisAuthCodeCache(cmdable)
	authCodeRepository := repository.NewAuthCodeRepositoryWithCache(authCodeCache)
	smsService := ioc.InitSMSService()
	authCodeService := service.NewAuthCodeServiceV1(authCodeRepository, smsService)
	userHandler := web.NewUserHandler(userService, authCodeService)
	engine := ioc.InitGinWebServer(v, userHandler)
	return engine
}
